name: Build Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js version 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Npm install
      run: npm install
    - name: Run the unit tests
      run: npm run test:unit
    - name: Display softuni username
      run: echo "karajov15"
  
  build_ui_test:
    runs-on: ubuntu-latest
    needs: build_test

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js version 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Npm install
      run: npm install
    - name: Install PlayWright
      run: npx playwright install
    - name: Run the UI tests
      run: npm run test:ui